# Generated by Django 3.2.25 on 2026-09-20 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('car', 'Car Rental'), ('bike', 'Bike Rental'), ('hall', 'Event Hall'), ('house', 'Residential House'), ('office', 'Commercial Office'), ('feedback', 'Customer Feedback')], default='car', max_length=20)),
                ('item_title', models.CharField(max_length=200)),
                ('item_id', models.IntegerField(default=0)),
                ('applicant_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('booking_date', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment_time', models.CharField(blank=True, max_length=100, null=True)),
                ('guests_or_km', models.CharField(blank=True, max_length=100, null=True)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
