# Generated by Django 3.2.25 on 2026-09-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginquiry',
            name='payment_method',
            field=models.CharField(default='COD at Showroom', max_length=50),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
