# Generated by Django 3.2.25 on 2026-09-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager', '0002_auto_20260920_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
