# Generated by Django 3.2.25 on 2026-09-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager', '0003_alter_bookinginquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginquiry',
            name='extra_fee_status',
            field=models.CharField(default='No Extra Fee', max_length=50),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='extra_km_driven',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='extra_km_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='extra_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
