# Generated by Django 3.2.25 on 2026-09-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager', '0004_auto_20260920_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginquiry',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='budget_max',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='budget_min',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='capacity_needed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='inquiry_type',
            field=models.CharField(default='hall', max_length=20),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='location_preference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='meeting_location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='meeting_type',
            field=models.CharField(default='Google Meet', max_length=50),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='quoted_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='representative_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='representative_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookinginquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
