# Generated by Django 3.2.25 on 2026-09-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager', '0005_auto_20260921_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginquiry',
            name='end_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='hours_needed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='num_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='start_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
