# Generated by Django 3.2.25 on 2026-09-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager', '0006_auto_20260921_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginquiry',
            name='extra_fee_payment_mode',
            field=models.CharField(default='Razorpay', max_length=50),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='showroom_otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
