from django.urls import path
from . import views

app_name = 'admin_app'

urlpatterns = [
    path('login/', views.admin_login_page, name='login'),
    path('dashboard/', views.admin_dashboard_page, name='dashboard'),
    path('manage-vehicles/', views.admin_manage_vehicles_page, name='manage_vehicles'),
    path('manage-cars/', views.admin_manage_cars_page, name='manage_cars'),
    path('manage-bikes/', views.admin_manage_bikes_page, name='manage_bikes'),
    path('manage-categories/', views.admin_manage_categories_page, name='manage_categories'),
    path('api/categories/add/', views.admin_add_category_api, name='api_add_category'),
    path('api/categories/delete/', views.admin_delete_category_api, name='api_delete_category'),
    path('api/features/add/', views.admin_add_feature_api, name='api_add_feature'),
    path('api/features/delete/', views.admin_delete_feature_api, name='api_delete_feature'),

    path('manage-halls/', views.admin_manage_halls_page, name='manage_halls'),
    path('manage-houses/', views.admin_manage_houses_page, name='manage_houses'),
    path('manage-offices/', views.admin_manage_offices_page, name='manage_offices'),
    path('manage-bookings/', views.admin_manage_bookings_page, name='manage_bookings'),
    path('manage-status-updates/', views.admin_manage_status_updates_page, name='manage_status_updates'),
    path('view-inquiries/', views.admin_view_inquiries_page, name='view_inquiries'),
    path('view-house-inquiries/', views.admin_view_house_inquiries_page, name='view_house_inquiries'),
    path('view-office-inquiries/', views.admin_view_office_inquiries_page, name='view_office_inquiries'),
    path('view-feedback/', views.admin_view_feedback_page, name='view_feedback'),
    path('edit-hall/', views.admin_edit_hall_page, name='edit_hall'),
    path('edit-house/', views.admin_edit_house_page, name='edit_house'),
    path('edit-office/', views.admin_edit_office_page, name='edit_office'),
    path('api/cars/add/', views.admin_add_car_api, name='api_add_car'),
    path('api/cars/edit/', views.admin_edit_car_api, name='api_edit_car'),
    path('api/cars/delete/', views.admin_delete_car_api, name='api_delete_car'),
    path('api/bikes/add/', views.admin_add_bike_api, name='api_add_bike'),
    path('api/bikes/edit/', views.admin_edit_bike_api, name='api_edit_bike'),
    path('api/bikes/delete/', views.admin_delete_bike_api, name='api_delete_bike'),
    path('api/halls/add/', views.admin_add_hall_api, name='api_add_hall'),
    path('api/halls/edit/', views.admin_edit_hall_api, name='api_edit_hall'),
    path('api/halls/delete/', views.admin_delete_hall_api, name='api_delete_hall'),
    path('api/halls/live-list/', views.admin_live_halls_api, name='api_live_halls'),
    path('api/houses/add/', views.admin_add_house_api, name='api_add_house'),
    path('api/houses/edit/', views.admin_edit_house_api, name='api_edit_house'),
    path('api/houses/delete/', views.admin_delete_house_api, name='api_delete_house'),
    path('api/houses/live-list/', views.admin_live_houses_api, name='api_live_houses'),
    path('api/offices/add/', views.admin_add_office_api, name='api_add_office'),
    path('api/offices/edit/', views.admin_edit_office_api, name='api_edit_office'),
    path('api/offices/delete/', views.admin_delete_office_api, name='api_delete_office'),
    path('api/offices/live-list/', views.admin_live_offices_api, name='api_live_offices'),
    path('api/vehicles/toggle-engine-lock/', views.admin_toggle_engine_lock_api, name='api_toggle_engine_lock'),
    path('api/bookings/update-status/', views.admin_update_booking_status_api, name='api_update_booking_status'),
    path('api/bookings/add-extra-charge/', views.admin_add_extra_charge_api, name='api_add_extra_charge'),
    path('api/bookings/confirm-extra-fee/', views.admin_confirm_extra_fee_api, name='api_confirm_extra_fee'),
    path('api/bookings/live-list/', views.admin_live_bookings_api, name='api_live_bookings'),
    path('api/halls/inquiries-live-list/', views.admin_live_hall_inquiries_api, name='api_live_hall_inquiries'),
    path('api/houses/inquiries-live-list/', views.admin_live_house_inquiries_api, name='api_live_house_inquiries'),
    path('api/offices/inquiries-live-list/', views.admin_live_office_inquiries_api, name='api_live_office_inquiries'),
    path('api/feedback/live-list/', views.admin_live_feedback_api, name='api_live_feedback'),
    path('api/inquiries/respond/', views.admin_respond_property_inquiry_api, name='api_respond_property_inquiry'),
    path('manage-verifications/', views.admin_manage_verifications_page, name='manage_verifications'),
    path('api/update-verification/', views.admin_update_verification_api, name='api_update_verification'),
    path('manage-payments/', views.admin_manage_payments_page, name='manage_payments'),
    path('api/verify-showroom-otp/', views.admin_verify_showroom_otp_api, name='api_verify_showroom_otp'),
    path('api/payments/live-list/', views.admin_live_payments_api, name='api_live_payments'),
]
