# Generated by Django 3.2.25 on 2026-09-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(default='IT Tech Suite', max_length=100)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('workstations', models.IntegerField(default=25)),
                ('conference_rooms', models.IntegerField(default=2)),
                ('area_sqft', models.CharField(default='1800 sq.ft', max_length=50)),
                ('ac_type', models.CharField(default='VRV Central AC', max_length=50)),
                ('parking', models.CharField(default='4 Underground Slots', max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('amenities', models.TextField(blank=True, default='High-Speed Fiber Internet, Server Room, Pantry, 24/7 Biometric Access')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Maintenance', 'Under Maintenance')], default='Available', max_length=20)),
                ('image', models.TextField(blank=True, default='/static/images/image/c1.jpg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(default='Marriage Banquet', max_length=100)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=12)),
                ('capacity', models.IntegerField(default=500)),
                ('ac_type', models.CharField(default='Central AC', max_length=50)),
                ('parking', models.CharField(default='150 Vehicles', max_length=100)),
                ('catering_policy', models.CharField(default='In-House Pure Veg', max_length=100)),
                ('stage_dj_setup', models.CharField(default='LED Stage Screen + DJ Console Included', max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('amenities', models.TextField(blank=True, default='2 Luxury AC Bridal Rooms, 24/7 Power Backup, Valet Parking')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Maintenance', 'Under Maintenance')], default='Available', max_length=20)),
                ('image', models.TextField(blank=True, default='/static/images/image/c1.jpg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(default='Luxury Villa', max_length=100)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bedrooms', models.IntegerField(default=3)),
                ('bathrooms', models.IntegerField(default=3)),
                ('area_sqft', models.CharField(default='2400 sq.ft', max_length=50)),
                ('furnishing', models.CharField(default='Fully Furnished', max_length=50)),
                ('parking', models.CharField(default='2 Car Covered Garage', max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('amenities', models.TextField(blank=True, default='Private Swimming Pool, Solar Power, 24/7 Gated Security')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented'), ('Maintenance', 'Under Maintenance')], default='Available', max_length=20)),
                ('image', models.TextField(blank=True, default='/static/images/image/c1.jpg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
