# Generated by Django 3.2.25 on 2026-09-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='document_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_document_type',
            field=models.CharField(choices=[('Driving License', 'Driving License'), ('Aadhaar Card', 'Aadhaar Card'), ('Passport', 'Passport'), ('Voter ID', 'Voter ID')], default='Driving License', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_status',
            field=models.CharField(choices=[('Unverified', 'Unverified'), ('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
