# Generated by Django 3.2.25 on 2026-09-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(default='Cruiser', max_length=50)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('engine_cc', models.CharField(default='350cc', max_length=50)),
                ('power_hp', models.CharField(default='20.2 BHP', max_length=50)),
                ('average_mileage', models.CharField(default='38 kmpl', max_length=50)),
                ('start_km', models.IntegerField(default=5000)),
                ('end_km', models.IntegerField(default=5200)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Maintenance', 'Under Maintenance')], default='Available', max_length=20)),
                ('image', models.TextField(blank=True, default='/static/images/image/carimg/kia.jpg')),
                ('return_image', models.TextField(blank=True, default='/static/images/image/carimg/kia.jpg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(default='SUV', max_length=50)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seats', models.IntegerField(default=5)),
                ('transmission', models.CharField(default='Automatic', max_length=20)),
                ('start_km', models.IntegerField(default=10000)),
                ('end_km', models.IntegerField(default=10200)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Maintenance', 'Under Maintenance')], default='Available', max_length=20)),
                ('image', models.TextField(blank=True, default='/static/images/image/carimgs/thar1.jpg')),
                ('return_image', models.TextField(blank=True, default='/static/images/image/carimgs/thar1.jpg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
