# Generated by Django 3.2.25 on 2026-09-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='description',
            field=models.TextField(blank=True, default='High performance two-wheeler built for smooth riding, excellent fuel efficiency, and road comfort.'),
        ),
        migrations.AddField(
            model_name='bike',
            name='features',
            field=models.TextField(blank=True, default='Dual Channel ABS, Electric Start, Digital Console, Alloy Wheels, Disc Brakes'),
        ),
        migrations.AddField(
            model_name='bike',
            name='fuel_type',
            field=models.CharField(default='Petrol', max_length=30),
        ),
        migrations.AddField(
            model_name='bike',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.8, max_digits=3),
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, default='Feature-loaded vehicle for comfortable city commuting and highway road trips.'),
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.TextField(blank=True, default='4x4 Drive, Climate Control AC, Touchscreen Infotainment, Dual Airbags, ABS with EBD'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='Petrol', max_length=30),
        ),
        migrations.AddField(
            model_name='car',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.9, max_digits=3),
        ),
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.TextField(blank=True, default='/static/images/image/bikeimg/bullet.jpg'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='return_image',
            field=models.TextField(blank=True, default='/static/images/image/bikeimg/bullet.jpg'),
        ),
    ]
