# Generated by Django 3.2.25 on 2026-09-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rentals', '0002_auto_20260920_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='allowed_km_per_day',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='bike',
            name='engine_status',
            field=models.CharField(default='UNLOCKED', max_length=20),
        ),
        migrations.AddField(
            model_name='bike',
            name='extra_km_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='bike',
            name='gps_lat',
            field=models.CharField(default='21.7645', max_length=50),
        ),
        migrations.AddField(
            model_name='bike',
            name='gps_lng',
            field=models.CharField(default='72.1519', max_length=50),
        ),
        migrations.AddField(
            model_name='bike',
            name='ignition_status',
            field=models.CharField(default='OFF', max_length=20),
        ),
        migrations.AddField(
            model_name='bike',
            name='inspection_status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Verified', max_length=30),
        ),
        migrations.AddField(
            model_name='bike',
            name='location_name',
            field=models.CharField(default='Bhavnagar Station Road', max_length=150),
        ),
        migrations.AddField(
            model_name='car',
            name='allowed_km_per_day',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_status',
            field=models.CharField(default='UNLOCKED', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='extra_km_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='car',
            name='gps_lat',
            field=models.CharField(default='21.7645', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='gps_lng',
            field=models.CharField(default='72.1519', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='ignition_status',
            field=models.CharField(default='OFF', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='inspection_status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Verified', max_length=30),
        ),
        migrations.AddField(
            model_name='car',
            name='location_name',
            field=models.CharField(default='Bhavnagar Central Hub', max_length=150),
        ),
    ]
